apiVersion: v1
kind: Pod
metadata:
  name: rest-management
  labels:
    app.kubernetes.io/name: rest-management
spec:
  containers:
    - name: rest-management
      image: f2js/rest-management:latest
      ports:
        - containerPort: 8080
